[package]
name = "not_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
crossterm = "0.27.0"
figlet-rs = "0.1.5"
ratatui = "0.26.1"
tui-big-text = "0.4.1"
